const RESET_SEARCH = "RESET_SEARCH"
const RESET_SELECTED_MARKER = "RESET_SELECTED_MARKER"
const ADDED_LINE_POINT = "ADDED_LINE_POINT"
const REMOVED_POLYLINE = "REMOVED_POLYLINE"
const ADDED_POLYGON_POINT = "ADDED_POLYGON_POINT"
const REMOVED_POLYGON = "REMOVED_POLYGON"
const ADDED_CIRCLE_POINT = "ADDED_CIRCLE_POINT"
const REMOVED_CIRCLE = "REMOVED_CIRCLE"
const ADDED_TEXT_POINT = "ADDED_TEXT_POINT"
const REMOVED_TEXT = "REMOVED_TEXT"
const UPDATED_ANNOTATION_TEXT = "UPDATED_ANNOTATION_TEXT"
const FILTERED_MARKERS = "FILTERED_MARKERS"
const MAIN_UPDATED_ADDRESS = "MAIN_UPDATED_ADDRESS"
const MAIN_SELECTED_ADDRESS = "MAIN_SELECTED_ADDRESS"
const UPDATED_LOCATION = "UPDATED_LOCATION"
const UPDATED_MY_ADDRESS = "UPDATED_MY_ADDRESS"
const UPDATED_ROUTE = "UPDATED_ROUTE"
const SELECTED_ADDRESS = "SELECTED_ADDRESS"
const CURRENT_COUNTRY = "CURRENT_COUNTRY"
const ADDED_TO_ROUTE = "ADDED_TO_ROUTE"

export default {
    RESET_SEARCH,
    RESET_SELECTED_MARKER,
    ADDED_LINE_POINT,
    REMOVED_POLYLINE,
    ADDED_POLYGON_POINT,
    REMOVED_POLYGON,
    ADDED_CIRCLE_POINT,
    REMOVED_CIRCLE,
    ADDED_TEXT_POINT,
    REMOVED_TEXT,
    UPDATED_ANNOTATION_TEXT,
    FILTERED_MARKERS,
    MAIN_UPDATED_ADDRESS,
    MAIN_SELECTED_ADDRESS,
    UPDATED_LOCATION,
    UPDATED_MY_ADDRESS,
    UPDATED_ROUTE,
    SELECTED_ADDRESS,
    CURRENT_COUNTRY,
    ADDED_TO_ROUTE
}
